# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b82d030eb461879088a195c4148ef95548507f8a1d36d3cac163517fa244c2731c6db8b6de2f3168f4331869db9d53efa6cd95ecc3027a7713154c8b4d2992

test:
  secret_key_base: 72eac72dd39a780aa94aa44b2f7dcdf7e205d1755ab2db1ad1993bd8b9fdc5ee360ed47ab3a84690b10077d97cd6c21bf488b2769ac37ee808c380bd4da9d99a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
